---
#server.port: 8082

# ===============================
# = DATA SOURCE
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/barclays_hiring
    username: root
    password: P@ssw0rd

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

STRIPE_PUBLIC_KEY: pk_test_51ICfNaCrEm87RQhZREZdFioXwyeA55DihPMrZOodimebeFbbms2Y4579ygvqzaaWXvCaUhlUiN2xHf3Upq8srqfg00TdByiboQ
STRIPE_SECRET_KEY: sk_test_51ICfNaCrEm87RQhZA4RNP1mQttH6iDlVc1RA7T90kAF5RcxkrZelGJFGqHiSGtBtw3xl8qabcBk6jRXZ6Io5lMQM00j6SkwZIk

DOMAIN_BASE_URL: http://localhost:8082